AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Quarkus IoT Serverless - Migration from Spring Boot ECS to Lambda

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: provided.al2
    Architectures:
      - x86_64
    Environment:
      Variables:
        QUARKUS_LAMBDA_HANDLER: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler
        DYNAMODB_SENSOR_DATA_TABLE_NAME: !Ref SensorDataTable
        DYNAMODB_RUNS_TABLE_NAME: !Ref RunsTable
        APP_RUN_MAX_CONCURRENT: 5

Parameters:
  GrafanaBaseUrl:
    Type: String
    Default: "http://localhost:3000"
    Description: Base URL for Grafana dashboard
  
  GrafanaDashboardPath:
    Type: String
    Default: "/d/iot-dashboard"
    Description: Path to Grafana dashboard

Resources:
  # DynamoDB Tables
  SensorDataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SensorData
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: sensorId
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: sensorId
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      Tags:
        - Key: Project
          Value: quarkus-iot-lambda
        - Key: Migration
          Value: spring-boot-to-quarkus

  RunsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Runs
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      Tags:
        - Key: Project
          Value: quarkus-iot-lambda
        - Key: Migration
          Value: spring-boot-to-quarkus

  # Lambda Function
  QuarkusIoTLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: quarkus-iot-lambda
      CodeUri: target/function.zip
      Handler: not.used.in.provided.runtime
      Environment:
        Variables:
          APP_GRAFANA_BASE_URL: !Ref GrafanaBaseUrl
          APP_GRAFANA_DASHBOARD_PATH: !Ref GrafanaDashboardPath
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SensorDataTable
        - DynamoDBCrudPolicy:
            TableName: !Ref RunsTable
        - CloudWatchPutMetricPolicy: {}
      Events:
        ProxyApiRoot:
          Type: Api
          Properties:
            RestApiId: !Ref IoTApi
            Path: /
            Method: ANY
        ProxyApiGreedy:
          Type: Api
          Properties:
            RestApiId: !Ref IoTApi
            Path: /{proxy+}
            Method: ANY

  # API Gateway
  IoTApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: QuarkusIoTLambdaAPI
      StageName: prod
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-User'"
        AllowOrigin: "'*'"
      Auth:
        ApiKeyRequired: false
      DefinitionBody:
        swagger: "2.0"
        info:
          title: "Quarkus IoT Lambda API"
          version: "1.0"
        paths:
          /:
            x-amazon-apigateway-any-method:
              produces:
                - application/json
              responses:
                "200":
                  description: "200 response"
              x-amazon-apigateway-integration:
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${QuarkusIoTLambda.Arn}/invocations"
                passthroughBehavior: "when_no_match"
                httpMethod: "POST"
                type: "aws_proxy"
          /{proxy+}:
            x-amazon-apigateway-any-method:
              produces:
                - application/json
              parameters:
                - name: proxy
                  in: path
                  required: true
                  type: string
              responses: {}
              x-amazon-apigateway-integration:
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${QuarkusIoTLambda.Arn}/invocations"
                passthroughBehavior: "when_no_match"
                httpMethod: "POST"
                type: "aws_proxy"

  # CloudWatch Log Group
  QuarkusIoTLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${QuarkusIoTLambda}"
      RetentionInDays: 7

  # CloudWatch Alarm for Errors
  LambdaErrorsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: quarkus-iot-lambda-errors
      AlarmDescription: Alert when Lambda function has errors
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref QuarkusIoTLambda

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${IoTApi}.execute-api.${AWS::Region}.amazonaws.com/prod/"
    Export:
      Name: !Sub "${AWS::StackName}-ApiEndpoint"

  LambdaFunctionArn:
    Description: "Quarkus IoT Lambda Function ARN"
    Value: !GetAtt QuarkusIoTLambda.Arn
    Export:
      Name: !Sub "${AWS::StackName}-FunctionArn"

  SensorDataTableName:
    Description: "DynamoDB SensorData Table Name"
    Value: !Ref SensorDataTable
    Export:
      Name: !Sub "${AWS::StackName}-SensorDataTable"

  RunsTableName:
    Description: "DynamoDB Runs Table Name"
    Value: !Ref RunsTable
    Export:
      Name: !Sub "${AWS::StackName}-RunsTable"
